apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  source:
    repoURL: https://charts.crossplane.io/stable
    chart: crossplane
    targetRevision: "1.16.0"
    helm:
      values: |
        replicas: 2
        leaderElection: true
        resourcesCrossplane:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            memory: 1Gi
        resourcesRBACManager:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 512Mi
        metrics:
          enabled: true
        # Limit provider pods to sane defaults; providers override via
        # DeploymentRuntimeConfig in gitops/crossplane/providers/
        provider:
          packages: []
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
